using System;
using System.Collections.Generic;
using System.Text;
using ImageHub.Models;
using ImageHub.Support;

namespace ImageHub.Services;

/// <summary>Secrets pulled out of the store for exactly the duration of a build.</summary>
public sealed class ResolvedSecrets
{
    public string AdminPassword { get; set; } = string.Empty;

    public string UserPassword { get; set; } = string.Empty;

    public string DomainPassword { get; set; } = string.Empty;

    public string ProductKey { get; set; } = string.Empty;

    public string WifiPassword { get; set; } = string.Empty;

    public static ResolvedSecrets Load(DeploymentTemplate template) => new()
    {
        AdminPassword = SecretStore.Get(template.Id, SecretSlot.AdminPassword) ?? string.Empty,
        UserPassword = SecretStore.Get(template.Id, SecretSlot.UserPassword) ?? string.Empty,
        DomainPassword = SecretStore.Get(template.Id, SecretSlot.DomainPassword) ?? string.Empty,
        ProductKey = SecretStore.Get(template.Id, SecretSlot.ProductKey) ?? string.Empty,
        WifiPassword = SecretStore.Get(template.Id, SecretSlot.WifiPassword) ?? string.Empty,
    };
}

/// <summary>
/// Generates the autounattend.xml that Windows Setup picks up automatically from
/// the root of the boot media.
///
/// A port of Sources/ImageHub/Services/AnswerFileBuilder.swift, and it has to stay
/// one: a drive built here must be interchangeable with a drive built on a Mac.
/// Every element, attribute and command string below matches that file. The
/// whitespace between elements does not — this writer indents properly, the Swift
/// one has some quirks — so CI compares the two files as parsed XML rather than as
/// text (scripts/compare_generated.py), which is the property Setup cares about.
///
/// The answer file deliberately does as little as possible: wipe and partition the
/// disk, pick the edition, create the IT admin account, stage the payload onto
/// C:\ImageHub, and then hand over to Provision.ps1. Everything else is PowerShell,
/// because PowerShell is debuggable on the target machine and unattend XML is not.
/// </summary>
public sealed class AnswerFileBuilder
{
    private readonly DeploymentTemplate _template;
    private readonly ResolvedSecrets _secrets;

    public AnswerFileBuilder(DeploymentTemplate template, ResolvedSecrets? secrets = null)
    {
        _template = template;
        _secrets = secrets ?? new ResolvedSecrets();
    }

    private string Architecture =>
        _template.Windows.Architecture.Equals("arm64", StringComparison.OrdinalIgnoreCase)
            ? "arm64" : "amd64";

    private bool IsUefi => _template.Disk.PartitionStyle == PartitionStyle.Gpt;

    /// <summary>Partition the OS lands on: EFI + MSR + Windows on GPT, single partition on MBR.</summary>
    private int WindowsPartitionId => IsUefi ? 3 : 1;

    public string Build()
    {
        var xml = new XmlText();
        xml.Raw("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
        xml.Raw("<!--");
        xml.Raw($"  Generated by ImageHub {AppVersion.Current} for template \"{_template.Name}\".");
        xml.Raw("  Regenerated on every build — edit the template, not this file.");
        xml.Raw("-->");
        xml.Raw("<unattend xmlns=\"urn:schemas-microsoft-com:unattend\" "
            + "xmlns:wcm=\"http://schemas.microsoft.com/WMIConfig/2002/State\">");
        xml.Indent();

        WindowsPePass(xml);
        SpecializePass(xml);
        OobeSystemPass(xml);

        xml.Outdent();
        xml.Raw("</unattend>");
        return xml.ToString();
    }

    // MARK: - windowsPE

    private void WindowsPePass(XmlText xml)
    {
        xml.Open("settings pass=\"windowsPE\"");

        Component(xml, "Microsoft-Windows-International-Core-WinPE", body =>
        {
            body.Open("SetupUILanguage");
            body.Element("UILanguage", Esc(_template.System.Locale));
            body.Close("SetupUILanguage");
            body.Element("InputLocale", Esc(_template.System.InputLocale));
            body.Element("SystemLocale", Esc(_template.System.Locale));
            body.Element("UILanguage", Esc(_template.System.Locale));
            body.Element("UserLocale", Esc(_template.System.Locale));
        });

        Component(xml, "Microsoft-Windows-Setup", body =>
        {
            // Element order inside a component is part of the unattend schema, and
            // Setup rejects the whole answer file when it's wrong rather than ignoring
            // the stray element. The sequence is DiskConfiguration, ImageInstall,
            // RunSynchronous, UserData — so the bypasses go in front of UserData.
            if (_template.Disk.WipeTargetDisk) { DiskConfiguration(body); }
            ImageInstall(body);
            RequirementBypass(body);
            UserData(body);
        });

        xml.Close("settings");
    }

    private void DiskConfiguration(XmlText xml)
    {
        xml.Open("DiskConfiguration");
        xml.Element("WillShowUI", "OnError");

        int[] ids = _template.Disk.WipeAllDisks
            ? new[] { 0, 1, 2, 3 }
            : new[] { _template.Disk.DiskNumber };

        foreach (int id in ids)
        {
            xml.Open("Disk wcm:action=\"add\"");
            xml.Element("DiskID", id.ToString());
            xml.Element("WillWipeDisk", "true");

            if (id == _template.Disk.DiskNumber)
            {
                xml.Open("CreatePartitions");
                if (IsUefi)
                {
                    xml.Open("CreatePartition wcm:action=\"add\"");
                    xml.Element("Order", "1");
                    xml.Element("Type", "EFI");
                    xml.Element("Size", _template.Disk.EfiSizeMb.ToString());
                    xml.Close("CreatePartition");

                    xml.Open("CreatePartition wcm:action=\"add\"");
                    xml.Element("Order", "2");
                    xml.Element("Type", "MSR");
                    xml.Element("Size", _template.Disk.MsrSizeMb.ToString());
                    xml.Close("CreatePartition");

                    // Windows takes the rest of the disk. Setup carves the WinRE
                    // partition off the end by itself; disk.recoveryPartition == false
                    // is handled later by `reagentc /disable` during provisioning.
                    xml.Open("CreatePartition wcm:action=\"add\"");
                    xml.Element("Order", "3");
                    xml.Element("Type", "Primary");
                    xml.Element("Extend", "true");
                    xml.Close("CreatePartition");
                }
                else
                {
                    xml.Open("CreatePartition wcm:action=\"add\"");
                    xml.Element("Order", "1");
                    xml.Element("Type", "Primary");
                    xml.Element("Extend", "true");
                    xml.Close("CreatePartition");
                }
                xml.Close("CreatePartitions");

                xml.Open("ModifyPartitions");
                if (IsUefi)
                {
                    xml.Open("ModifyPartition wcm:action=\"add\"");
                    xml.Element("Order", "1");
                    xml.Element("PartitionID", "1");
                    xml.Element("Label", "System");
                    xml.Element("Format", "FAT32");
                    xml.Close("ModifyPartition");

                    xml.Open("ModifyPartition wcm:action=\"add\"");
                    xml.Element("Order", "2");
                    xml.Element("PartitionID", "3");
                    xml.Element("Label", "Windows");
                    xml.Element("Format", "NTFS");
                    xml.Close("ModifyPartition");
                }
                else
                {
                    xml.Open("ModifyPartition wcm:action=\"add\"");
                    xml.Element("Order", "1");
                    xml.Element("PartitionID", "1");
                    xml.Element("Label", "Windows");
                    xml.Element("Letter", "C");
                    xml.Element("Format", "NTFS");
                    xml.Element("Active", "true");
                    xml.Close("ModifyPartition");
                }
                xml.Close("ModifyPartitions");
            }

            xml.Close("Disk");
        }

        xml.Close("DiskConfiguration");
    }

    private void ImageInstall(XmlText xml)
    {
        xml.Open("ImageInstall");
        xml.Open("OSImage");

        xml.Open("InstallFrom");
        xml.Open("MetaData wcm:action=\"add\"");
        if (_template.Windows.ImageIndex is int index)
        {
            xml.Element("Key", "/IMAGE/INDEX");
            xml.Element("Value", index.ToString());
        }
        else
        {
            xml.Element("Key", "/IMAGE/NAME");
            xml.Element("Value", Esc(
                WindowsEditions.ImageName(_template.Windows.Edition, _template.Windows.Release)));
        }
        xml.Close("MetaData");
        xml.Close("InstallFrom");

        xml.Open("InstallTo");
        xml.Element("DiskID", _template.Disk.DiskNumber.ToString());
        xml.Element("PartitionID", WindowsPartitionId.ToString());
        xml.Close("InstallTo");

        xml.Element("WillShowUI", "OnError");
        xml.Close("OSImage");
        xml.Close("ImageInstall");
    }

    private void UserData(XmlText xml)
    {
        xml.Open("UserData");

        switch (_template.Windows.ProductKeyMode)
        {
            // None and Firmware both leave <ProductKey> out. Setup then falls back to
            // the OEM key in the firmware's MSDM table, or to the machine's digital
            // licence, and activates on its own. Writing a key here is what blocks
            // that — the edition comes from /IMAGE/NAME in ImageInstall, never from
            // the key, so dropping it costs nothing.
            case ProductKeyMode.None:
            case ProductKeyMode.Firmware:
                break;

            case ProductKeyMode.Generic:
                string? generic = WindowsEditions.GenericKey(
                    _template.Windows.Edition, _template.Windows.Release);
                if (!string.IsNullOrEmpty(generic))
                {
                    xml.Open("ProductKey");
                    xml.Element("Key", generic);
                    xml.Element("WillShowUI", "OnError");
                    xml.Close("ProductKey");
                }
                break;

            case ProductKeyMode.Custom:
                if (_secrets.ProductKey.Length > 0)
                {
                    xml.Open("ProductKey");
                    xml.Element("Key", Esc(_secrets.ProductKey));
                    xml.Element("WillShowUI", "OnError");
                    xml.Close("ProductKey");
                }
                break;
        }

        xml.Element("AcceptEula", Bool(_template.Windows.AcceptEula));
        xml.Element("FullName", Esc(_template.Admin.DisplayName));
        xml.Element("Organization", "ImageHub");
        xml.Close("UserData");
    }

    /// <summary>
    /// Sets the LabConfig keys Windows Setup checks for TPM / Secure Boot / RAM.
    /// LabConfig only, and only in windowsPE — this writes into WinPE's own registry,
    /// which is exactly where Setup reads the hardware-check bypasses from. BypassNRO
    /// is *not* set here: in windowsPE, HKLM is WinPE's hive, so the value would
    /// vanish with the RAM disk. It's applied in specialize instead, where HKLM is the
    /// installed system.
    /// </summary>
    private void RequirementBypass(XmlText xml)
    {
        if (!_template.System.BypassWin11Requirements) { return; }
        string[] labConfig =
        {
            "BypassTPMCheck", "BypassSecureBootCheck", "BypassRAMCheck",
            "BypassCPUCheck", "BypassStorageCheck",
        };
        var commands = new List<string>();
        foreach (string name in labConfig)
        {
            commands.Add($@"cmd /c reg add HKLM\SYSTEM\Setup\LabConfig /v {name} /t REG_DWORD /d 1 /f");
        }
        RunSynchronous(xml, commands);
    }

    // MARK: - specialize

    private void SpecializePass(XmlText xml)
    {
        xml.Open("settings pass=\"specialize\"");

        Component(xml, "Microsoft-Windows-Shell-Setup", body =>
        {
            body.Element("ComputerName", "*");
            body.Element("TimeZone", Esc(_template.System.TimeZone));
            if (_template.Identity.JoinMode == JoinMode.Workgroup
                && _template.Identity.Workgroup.Length > 0)
            {
                body.Raw("<!-- Workgroup is applied by Provision.ps1 -->");
            }
        });

        // Stage the payload onto the system drive first so provisioning keeps working
        // after the USB stick is pulled out.
        var commands = new List<string> { StagePayloadCommand };
        if (_template.System.BypassNetworkRequirement)
        {
            // Has to be here rather than windowsPE: OOBE reads it from the installed
            // system's registry, and in windowsPE HKLM is the RAM disk.
            commands.Add(
                @"cmd /c reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE"
                + " /v BypassNRO /t REG_DWORD /d 1 /f");
        }
        if (_template.System.EnableRemoteDesktop)
        {
            commands.Add(
                "cmd /c reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\""
                + " /v fDenyTSConnections /t REG_DWORD /d 0 /f");
        }
        foreach (CustomScript script in _template.Scripts)
        {
            if (script.Enabled && script.Phase == ScriptPhase.Specialize)
            {
                commands.Add(SpecializeScriptCommand(script));
            }
        }
        Component(xml, "Microsoft-Windows-Deployment", body => RunSynchronous(body, commands));

        if (_template.Identity.JoinMode == JoinMode.ActiveDirectory
            && _template.Identity.Domain.Length > 0)
        {
            Component(xml, "Microsoft-Windows-UnattendedJoin", body =>
            {
                body.Open("Identification");
                body.Open("Credentials");
                body.Element("Domain", Esc(_template.Identity.Domain));
                body.Element("Username", Esc(_template.Identity.DomainJoinUser));
                body.Element("Password", Esc(_secrets.DomainPassword));
                body.Close("Credentials");
                body.Element("JoinDomain", Esc(_template.Identity.Domain));
                if (_template.Identity.OrganizationalUnit.Length > 0)
                {
                    body.Element("MachineObjectOU", Esc(_template.Identity.OrganizationalUnit));
                }
                body.Close("Identification");
            });
        }

        if (_template.System.EnableRemoteDesktop)
        {
            Component(xml, "Microsoft-Windows-TerminalServices-LocalSessionManager",
                body => body.Element("fDenyTSConnections", "false"));
        }

        xml.Close("settings");
    }

    /// <summary>
    /// Copies &lt;usb&gt;\ImageHub to C:\ImageHub. The drive letter of the USB stick is
    /// unknowable ahead of time, so the payload is found by marker file.
    ///
    /// RunSynchronousCommand/Path is capped at 259 characters. The inline PowerShell
    /// that used to live here came to 324, so Windows rejected the *entire* unattend
    /// file at oobeSystem — "Value is invalid", 0x80220005 — after the image had
    /// already been applied, leaving the machine in the "computer restarted
    /// unexpectedly" loop. The scan still has to happen at runtime, so it moved into
    /// Stage.cmd on the media and this is just short enough to find and call it.
    /// </summary>
    private static string StagePayloadCommand =>
        "cmd /c for %d in (C D E F G H I J K L M N O P Q R S T U V W X Y Z) do "
        + @"@if exist %d:\ImageHub\Stage.cmd call %d:\ImageHub\Stage.cmd";

    private static string SpecializeScriptCommand(CustomScript script)
    {
        string file = @"C:\ImageHub\Scripts\" + PayloadBuilder.ScriptFileName(script);
        return PowerShellCommand($"if (Test-Path '{file}') {{ & '{file}' }}");
    }

    // MARK: - oobeSystem

    private void OobeSystemPass(XmlText xml)
    {
        xml.Open("settings pass=\"oobeSystem\"");

        Component(xml, "Microsoft-Windows-International-Core", body =>
        {
            body.Element("InputLocale", Esc(_template.System.InputLocale));
            body.Element("SystemLocale", Esc(_template.System.Locale));
            body.Element("UILanguage", Esc(_template.System.Locale));
            body.Element("UserLocale", Esc(_template.System.Locale));
        });

        Component(xml, "Microsoft-Windows-Shell-Setup", body =>
        {
            body.Element("TimeZone", Esc(_template.System.TimeZone));
            body.Open("OOBE");
            body.Element("HideEULAPage", Bool(_template.Oobe.HideEula));
            body.Element("HideOEMRegistrationScreen", Bool(_template.Oobe.HideOemRegistration));
            body.Element("HideOnlineAccountScreens", Bool(_template.Oobe.HideOnlineAccountScreens));
            body.Element("HideWirelessSetupInOOBE", Bool(_template.Oobe.HideWirelessSetup));
            body.Element("ProtectYourPC", _template.Oobe.ProtectYourPc.ToString());
            body.Element("SkipMachineOOBE", Bool(_template.Oobe.SkipMachineOobe));
            body.Element("SkipUserOOBE", Bool(_template.Oobe.SkipUserOobe));
            body.Close("OOBE");

            UserAccounts(body);
            AutoLogon(body);
            FirstLogonCommands(body);
        });

        xml.Close("settings");
    }

    private void UserAccounts(XmlText xml)
    {
        bool hasAdmin = _template.Admin.Enabled && _template.Admin.Username.Length > 0;
        bool hasEndUser = _template.EndUser.Mode == EndUserMode.CreateLocalAccount
            && _template.EndUser.Username.Length > 0;
        if (!hasAdmin && !hasEndUser) { return; }

        xml.Open("UserAccounts");

        if (_template.Admin.EnableBuiltInAdministrator && _secrets.AdminPassword.Length > 0)
        {
            xml.Open("AdministratorPassword");
            xml.Element("Value", Esc(_secrets.AdminPassword));
            xml.Element("PlainText", "true");
            xml.Close("AdministratorPassword");
        }

        xml.Open("LocalAccounts");
        if (hasAdmin)
        {
            xml.Open("LocalAccount wcm:action=\"add\"");
            xml.Element("Name", Esc(_template.Admin.Username));
            xml.Element("DisplayName", Esc(_template.Admin.DisplayName));
            xml.Element("Description", Esc(_template.Admin.AccountDescription));
            xml.Element("Group", "Administrators");
            xml.Open("Password");
            xml.Element("Value", Esc(_secrets.AdminPassword));
            xml.Element("PlainText", "true");
            xml.Close("Password");
            xml.Close("LocalAccount");
        }
        if (hasEndUser)
        {
            string display = _template.EndUser.DisplayName.Length == 0
                ? _template.EndUser.Username
                : _template.EndUser.DisplayName;
            xml.Open("LocalAccount wcm:action=\"add\"");
            xml.Element("Name", Esc(_template.EndUser.Username));
            xml.Element("DisplayName", Esc(display));
            xml.Element("Description", "Created by ImageHub");
            xml.Element("Group", _template.EndUser.Administrator ? "Administrators" : "Users");
            xml.Open("Password");
            xml.Element("Value", Esc(_secrets.UserPassword));
            xml.Element("PlainText", "true");
            xml.Close("Password");
            xml.Close("LocalAccount");
        }
        xml.Close("LocalAccounts");

        xml.Close("UserAccounts");
    }

    private void AutoLogon(XmlText xml)
    {
        if (!_template.Admin.Enabled
            || _template.Admin.AutoLogonCount <= 0
            || _template.Admin.Username.Length == 0
            || _secrets.AdminPassword.Length == 0)
        {
            return;
        }

        xml.Open("AutoLogon");
        xml.Element("Enabled", "true");
        xml.Element("Username", Esc(_template.Admin.Username));
        xml.Element("LogonCount", _template.Admin.AutoLogonCount.ToString());
        xml.Open("Password");
        xml.Element("Value", Esc(_secrets.AdminPassword));
        xml.Element("PlainText", "true");
        xml.Close("Password");
        xml.Close("AutoLogon");
    }

    private void FirstLogonCommands(XmlText xml)
    {
        // Provisioning runs from C:\ImageHub (staged during specialize) with a drive
        // search as a fallback, but both live in Launch.cmd rather than here: the
        // inlined PowerShell reached 302 characters, and an over-length command string
        // invalidates the entire unattend file — reported only after the image is
        // applied.
        //
        // Launch.cmd is staged to C:\ImageHub by Stage.cmd, and searches the drives
        // itself if staging never happened.
        var commands = new List<(string Command, string Description)>
        {
            ("cmd /c for %d in (C D E F G H I J K L M N O P Q R S T U V W X Y Z) do "
                + @"@if exist %d:\ImageHub\Launch.cmd call %d:\ImageHub\Launch.cmd",
                "ImageHub provisioning"),
        };
        if (_template.Admin.HideFromLoginScreen && _template.Admin.Username.Length > 0)
        {
            commands.Add((
                "cmd /c reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon"
                + "\\SpecialAccounts\\UserList\" /v "
                + _template.Admin.Username + " /t REG_DWORD /d 0 /f",
                "Hide the IT admin account"));
        }

        xml.Open("FirstLogonCommands");
        for (int i = 0; i < commands.Count; i++)
        {
            xml.Open("SynchronousCommand wcm:action=\"add\"");
            xml.Element("Order", (i + 1).ToString());
            xml.Element("CommandLine", Esc(commands[i].Command));
            xml.Element("Description", Esc(commands[i].Description));
            xml.Element("RequiresUserInput", "false");
            xml.Close("SynchronousCommand");
        }
        xml.Close("FirstLogonCommands");
    }

    // MARK: - XML plumbing

    /// <summary>
    /// Writes a component, or nothing at all when the body turns out to be empty —
    /// the same rule the macOS builder applies, so a component with no settings never
    /// reaches Setup. The body is rendered into its own writer first, because "is it
    /// empty" can only be answered after building it.
    /// </summary>
    private void Component(XmlText xml, string name, Action<XmlText> body)
    {
        var inner = new XmlText(xml.Depth + 1);
        body(inner);
        string rendered = inner.ToString();
        if (rendered.Trim().Length == 0) { return; }

        xml.Raw($"<component name=\"{name}\" processorArchitecture=\"{Architecture}\" "
            + "publicKeyToken=\"31bf3856ad364e35\" language=\"neutral\" versionScope=\"nonSxS\">");
        xml.RawBlock(rendered);
        xml.Raw("</component>");
    }

    private static void RunSynchronous(XmlText xml, IReadOnlyList<string> commands)
    {
        if (commands.Count == 0) { return; }
        xml.Open("RunSynchronous");
        for (int i = 0; i < commands.Count; i++)
        {
            xml.Open("RunSynchronousCommand wcm:action=\"add\"");
            xml.Element("Order", (i + 1).ToString());
            xml.Element("Path", Esc(commands[i]));
            xml.Close("RunSynchronousCommand");
        }
        xml.Close("RunSynchronous");
    }

    private static string PowerShellCommand(string script)
    {
        string[] lines = script.Replace("\\\n", string.Empty).Split('\n');
        var parts = new List<string>(lines.Length);
        foreach (string line in lines) { parts.Add(line.Trim()); }
        return "powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \""
            + string.Join(" ", parts) + "\"";
    }

    private static string Bool(bool value) => value ? "true" : "false";

    private static string Esc(string value) => (value ?? string.Empty)
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;")
        .Replace("\"", "&quot;")
        .Replace("'", "&apos;");
}

/// <summary>
/// A very small indenting text writer.
///
/// Not XmlWriter: the answer file carries comments in specific places, element
/// names with a wcm:action attribute already baked into them, and text escaped
/// exactly the way the macOS side escapes it. Hand-writing keeps all three
/// obvious, and the output is a file a technician sometimes has to read.
/// </summary>
internal sealed class XmlText
{
    private readonly StringBuilder _text = new();
    private int _depth;

    public XmlText(int depth = 0) => _depth = depth;

    public int Depth => _depth;

    public void Indent() => _depth++;

    public void Outdent() => _depth = Math.Max(0, _depth - 1);

    public void Raw(string line) =>
        _text.Append(new string(' ', _depth * 2)).Append(line).Append('\n');

    /// <summary>Appends an already-rendered block, which carries its own indentation.</summary>
    public void RawBlock(string block) => _text.Append(block);

    public void Open(string tagWithAttributes)
    {
        Raw("<" + tagWithAttributes + ">");
        _depth++;
    }

    public void Close(string tag)
    {
        Outdent();
        Raw("</" + tag + ">");
    }

    public void Element(string tag, string value) => Raw($"<{tag}>{value}</{tag}>");

    public override string ToString() => _text.ToString();
}
