using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ImageHub.Models;

namespace ImageHub.Services;

/// <summary>
/// Builds the configuration.xml the Office Deployment Tool consumes.
///
/// Generated here rather than assembled by Provision.ps1 for the same reason
/// autounattend.xml is: it can be checked before the drive is written. A malformed
/// answer file costs a technician an afternoon at a bench, and a malformed Office
/// config costs the same afternoon a few steps later.
///
/// Reference: "Configuration options for the Office Deployment Tool". A port of
/// Sources/ImageHub/Services/OfficeConfigBuilder.swift.
/// </summary>
public static class OfficeConfigBuilder
{
    public const string FileName = "configuration.xml";

    /// <summary>
    /// Element order inside &lt;Configuration&gt; is not enforced the way the unattend
    /// schema is, but the ODT documents this sequence and there is nothing to gain
    /// from deviating: Add, RemoveMSI, Display, Property, Updates.
    /// </summary>
    public static string Xml(DeploymentTemplate template)
    {
        Microsoft365Spec office = template.Microsoft365;

        // The ODT only speaks in exclusions, so the template's "install these" list is
        // inverted here. Anything not asked for is left out, which also means a new app
        // appearing in a future Office release is excluded by default rather than
        // silently installed.
        var wanted = new HashSet<string>(office.IncludedApps, StringComparer.Ordinal);
        List<string> excluded = Microsoft365Spec.AvailableApps
            .Select(app => app.Id)
            .Where(id => !wanted.Contains(id))
            .Concat(Microsoft365Spec.AlwaysExcluded)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(id => id, StringComparer.Ordinal)
            .ToList();

        var text = new StringBuilder();
        text.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        text.Append("<!-- Generated by ImageHub. Edits here are overwritten on the next build. -->\n");
        text.Append("<Configuration>\n");
        text.Append($"  <Add OfficeClientEdition=\"{Esc(Microsoft365Spec.Architecture)}\" "
            + $"Channel=\"{Esc(Microsoft365Spec.ChannelId)}\">\n");
        text.Append($"    <Product ID=\"{Esc(Microsoft365Spec.ProductId)}\">\n");
        text.Append($"      <Language ID=\"{Esc(template.System.Locale.ToLowerInvariant())}\" />\n");
        foreach (string app in excluded)
        {
            text.Append($"      <ExcludeApp ID=\"{Esc(app)}\" />\n");
        }
        text.Append("    </Product>\n");
        text.Append("  </Add>\n");

        // RemoveMSI, Display and Updates are not choices. An older MSI Office left in
        // place breaks the new install; a visible installer waits for a human who is
        // not there; and Office with updates switched off is a liability.
        text.Append("  <RemoveMSI />\n");
        text.Append("  <Display Level=\"None\" AcceptEULA=\"TRUE\" />\n");
        text.Append("  <Property Name=\"FORCEAPPSHUTDOWN\" Value=\"TRUE\" />\n");
        text.Append("  <Updates Enabled=\"TRUE\" />\n");
        text.Append("</Configuration>\n");
        return text.ToString();
    }

    private static string Esc(string value) => (value ?? string.Empty)
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;")
        .Replace("\"", "&quot;")
        .Replace("'", "&apos;");
}
