import Foundation

/// Generates the `autounattend.xml` that Windows Setup picks up automatically
/// from the root of the boot media.
///
/// The answer file deliberately does as little as possible: wipe and partition
/// the disk, pick the edition, create the IT admin account, stage the payload
/// onto `C:\ImageHub`, and then hand over to `Provision.ps1`. Everything else is
/// PowerShell, because PowerShell is debuggable on the target machine and
/// unattend XML is not.
struct AnswerFileBuilder {
    let template: DeploymentTemplate
    let secrets: ResolvedSecrets

    /// Secrets pulled out of the Keychain for exactly the duration of a build.
    struct ResolvedSecrets {
        var adminPassword: String = ""
        var userPassword: String = ""
        var domainPassword: String = ""
        var productKey: String = ""
        var wifiPassword: String = ""

        static func load(for template: DeploymentTemplate) -> ResolvedSecrets {
            var secrets = ResolvedSecrets()
            secrets.adminPassword = SecretStore.get(for: template.id, slot: .adminPassword) ?? ""
            secrets.userPassword = SecretStore.get(for: template.id, slot: .userPassword) ?? ""
            secrets.domainPassword = SecretStore.get(for: template.id, slot: .domainPassword) ?? ""
            secrets.productKey = SecretStore.get(for: template.id, slot: .productKey) ?? ""
            secrets.wifiPassword = SecretStore.get(for: template.id, slot: .wifiPassword) ?? ""
            return secrets
        }
    }

    private var architecture: String {
        template.windows.architecture.lowercased() == "arm64" ? "arm64" : "amd64"
    }

    private var isUEFI: Bool { template.disk.partitionStyle == .gpt }

    /// Partition the OS lands on: EFI + MSR + Windows on GPT, single partition on MBR.
    private var windowsPartitionID: Int { isUEFI ? 3 : 1 }

    func build() -> String {
        var xml = """
            <?xml version="1.0" encoding="utf-8"?>
            <!--
              Generated by ImageHub \(AppVersion.current) for template "\(template.name)".
              Regenerated on every build — edit the template, not this file.
            -->
            <unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
            """
        xml += windowsPEPass()
        xml += specializePass()
        xml += oobeSystemPass()
        xml += "\n</unattend>\n"
        return xml
    }

    // MARK: - windowsPE

    private func windowsPEPass() -> String {
        var body = """

            <settings pass="windowsPE">
            \(component("Microsoft-Windows-International-Core-WinPE", body: """
                <SetupUILanguage>
                  <UILanguage>\(esc(template.system.locale))</UILanguage>
                </SetupUILanguage>
                <InputLocale>\(esc(template.system.inputLocale))</InputLocale>
                <SystemLocale>\(esc(template.system.locale))</SystemLocale>
                <UILanguage>\(esc(template.system.locale))</UILanguage>
                <UserLocale>\(esc(template.system.locale))</UserLocale>
            """))
            """

        var setupBody = ""
        if template.disk.wipeTargetDisk {
            setupBody += diskConfiguration()
        }
        setupBody += imageInstall()
        // Element order inside a component is part of the unattend schema, and
        // Setup rejects the whole answer file when it's wrong rather than
        // ignoring the stray element. The sequence here is DiskConfiguration,
        // ImageInstall, RunSynchronous, UserData — so the bypasses go in front of
        // UserData, not after it, where they used to be.
        if let bypass = requirementBypass() {
            setupBody += bypass
        }
        setupBody += userData()
        body += component("Microsoft-Windows-Setup", body: setupBody)
        body += "\n</settings>"
        return body
    }

    private func diskConfiguration() -> String {
        var partitions = ""
        var modifications = ""

        if isUEFI {
            partitions += """

                    <CreatePartition wcm:action="add">
                      <Order>1</Order>
                      <Type>EFI</Type>
                      <Size>\(template.disk.efiSizeMB)</Size>
                    </CreatePartition>
                    <CreatePartition wcm:action="add">
                      <Order>2</Order>
                      <Type>MSR</Type>
                      <Size>\(template.disk.msrSizeMB)</Size>
                    </CreatePartition>
                """
            modifications += """

                    <ModifyPartition wcm:action="add">
                      <Order>1</Order>
                      <PartitionID>1</PartitionID>
                      <Label>System</Label>
                      <Format>FAT32</Format>
                    </ModifyPartition>
                """

            // Windows takes the rest of the disk. Setup carves the WinRE
            // partition off the end by itself; `disk.recoveryPartition == false`
            // is handled later by `reagentc /disable` during provisioning.
            partitions += """

                    <CreatePartition wcm:action="add">
                      <Order>3</Order>
                      <Type>Primary</Type>
                      <Extend>true</Extend>
                    </CreatePartition>
                """
            modifications += """

                    <ModifyPartition wcm:action="add">
                      <Order>2</Order>
                      <PartitionID>3</PartitionID>
                      <Label>Windows</Label>
                      <Format>NTFS</Format>
                    </ModifyPartition>
                """
        } else {
            partitions += """

                    <CreatePartition wcm:action="add">
                      <Order>1</Order>
                      <Type>Primary</Type>
                      <Extend>true</Extend>
                    </CreatePartition>
                """
            modifications += """

                    <ModifyPartition wcm:action="add">
                      <Order>1</Order>
                      <PartitionID>1</PartitionID>
                      <Label>Windows</Label>
                      <Letter>C</Letter>
                      <Format>NTFS</Format>
                      <Active>true</Active>
                    </ModifyPartition>
                """
        }

        var disks = ""
        let ids = template.disk.wipeAllDisks ? Array(0...3) : [template.disk.diskNumber]
        for id in ids {
            disks += """

                  <Disk wcm:action="add">
                    <DiskID>\(id)</DiskID>
                    <WillWipeDisk>true</WillWipeDisk>
                """
            if id == template.disk.diskNumber {
                disks += """

                      <CreatePartitions>\(partitions)
                      </CreatePartitions>
                      <ModifyPartitions>\(modifications)
                      </ModifyPartitions>
                    """
            }
            disks += "\n      </Disk>"
        }

        return """

              <DiskConfiguration>
                <WillShowUI>OnError</WillShowUI>\(disks)
              </DiskConfiguration>
            """
    }

    private func imageInstall() -> String {
        var installFrom = ""
        if let index = template.windows.imageIndex {
            installFrom = """

                      <InstallFrom>
                        <MetaData wcm:action="add">
                          <Key>/IMAGE/INDEX</Key>
                          <Value>\(index)</Value>
                        </MetaData>
                      </InstallFrom>
                """
        } else {
            let name = template.windows.edition.imageName(for: template.windows.release)
            installFrom = """

                      <InstallFrom>
                        <MetaData wcm:action="add">
                          <Key>/IMAGE/NAME</Key>
                          <Value>\(esc(name))</Value>
                        </MetaData>
                      </InstallFrom>
                """
        }

        return """

              <ImageInstall>
                <OSImage>\(installFrom)
                  <InstallTo>
                    <DiskID>\(template.disk.diskNumber)</DiskID>
                    <PartitionID>\(windowsPartitionID)</PartitionID>
                  </InstallTo>
                  <WillShowUI>OnError</WillShowUI>
                </OSImage>
              </ImageInstall>
            """
    }

    private func userData() -> String {
        var key = ""
        switch template.windows.productKeyMode {
        case .none:
            key = ""
        case .generic:
            if let generic = template.windows.edition.genericKey(for: template.windows.release) {
                key = """

                        <ProductKey>
                          <Key>\(generic)</Key>
                          <WillShowUI>OnError</WillShowUI>
                        </ProductKey>
                    """
            }
        case .custom:
            if !secrets.productKey.isEmpty {
                key = """

                        <ProductKey>
                          <Key>\(esc(secrets.productKey))</Key>
                          <WillShowUI>OnError</WillShowUI>
                        </ProductKey>
                    """
            }
        }

        return """

              <UserData>\(key)
                <AcceptEula>\(template.windows.acceptEULA)</AcceptEula>
                <FullName>\(esc(template.admin.displayName))</FullName>
                <Organization>ImageHub</Organization>
              </UserData>
            """
    }

    /// Sets the LabConfig keys Windows Setup checks for TPM / Secure Boot / RAM.
    /// LabConfig only, and only in windowsPE — this writes into WinPE's own
    /// registry, which is exactly where Setup reads the hardware-check bypasses
    /// from. BypassNRO is *not* set here: in windowsPE, HKLM is WinPE's hive, so
    /// the value would vanish with the RAM disk. It's applied in specialize
    /// instead, where HKLM is the installed system.
    private func requirementBypass() -> String? {
        guard template.system.bypassWin11Requirements else { return nil }
        let labConfig = [
            "BypassTPMCheck", "BypassSecureBootCheck", "BypassRAMCheck",
            "BypassCPUCheck", "BypassStorageCheck"
        ]
        return runSynchronous(
            labConfig.map {
                #"cmd /c reg add HKLM\SYSTEM\Setup\LabConfig /v \#($0) /t REG_DWORD /d 1 /f"#
            }
        )
    }

    // MARK: - specialize

    private func specializePass() -> String {
        var body = "\n\n<settings pass=\"specialize\">"

        var shell = """

              <ComputerName>*</ComputerName>
              <TimeZone>\(esc(template.system.timeZone))</TimeZone>
            """
        if template.identity.joinMode == .workgroup && !template.identity.workgroup.isEmpty {
            shell += "\n      <!-- Workgroup is applied by Provision.ps1 -->"
        }
        body += component("Microsoft-Windows-Shell-Setup", body: shell)

        // Stage the payload onto the system drive first so provisioning keeps
        // working after the USB stick is pulled out.
        var commands: [String] = [stagePayloadCommand]
        if template.system.bypassNetworkRequirement {
            // Has to be here rather than windowsPE: OOBE reads it from the
            // installed system's registry, and in windowsPE HKLM is the RAM disk.
            commands.append(
                #"cmd /c reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE /v BypassNRO /t REG_DWORD /d 1 /f"#
            )
        }
        if template.system.enableRemoteDesktop {
            commands.append(
                #"cmd /c reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f"#
            )
        }
        for script in template.scripts where script.enabled && script.phase == .specialize {
            commands.append(specializeScriptCommand(script))
        }
        body += component("Microsoft-Windows-Deployment", body: runSynchronous(commands) ?? "")

        if template.identity.joinMode == .activeDirectory, !template.identity.domain.isEmpty {
            var identification = """

                  <Identification>
                    <Credentials>
                      <Domain>\(esc(template.identity.domain))</Domain>
                      <Username>\(esc(template.identity.domainJoinUser))</Username>
                      <Password>\(esc(secrets.domainPassword))</Password>
                    </Credentials>
                    <JoinDomain>\(esc(template.identity.domain))</JoinDomain>
                """
            if !template.identity.organizationalUnit.isEmpty {
                identification += "\n        <MachineObjectOU>\(esc(template.identity.organizationalUnit))</MachineObjectOU>"
            }
            identification += "\n      </Identification>"
            body += component("Microsoft-Windows-UnattendedJoin", body: identification)
        }

        if template.system.enableRemoteDesktop {
            body += component(
                "Microsoft-Windows-TerminalServices-LocalSessionManager",
                body: "\n      <fDenyTSConnections>false</fDenyTSConnections>"
            )
        }

        body += "\n</settings>"
        return body
    }

    /// Copies `<usb>\ImageHub` to `C:\ImageHub`. The drive letter of the USB
    /// stick is unknowable ahead of time, so the payload is found by marker file.
    private var stagePayloadCommand: String {
        let script = """
            $src = Get-PSDrive -PSProvider FileSystem | \
            ForEach-Object { Join-Path $_.Root 'ImageHub' } | \
            Where-Object { Test-Path (Join-Path $_ 'Provision.ps1') } | Select-Object -First 1; \
            if ($src) { Copy-Item -LiteralPath $src -Destination 'C:\\ImageHub' -Recurse -Force }
            """
        return powershellCommand(script)
    }

    private func specializeScriptCommand(_ script: CustomScript) -> String {
        let file = "C:\\ImageHub\\Scripts\\\(PayloadBuilder.scriptFileName(script))"
        return powershellCommand("if (Test-Path '\(file)') { & '\(file)' }")
    }

    // MARK: - oobeSystem

    private func oobeSystemPass() -> String {
        var body = "\n\n<settings pass=\"oobeSystem\">"

        body += component("Microsoft-Windows-International-Core", body: """

              <InputLocale>\(esc(template.system.inputLocale))</InputLocale>
              <SystemLocale>\(esc(template.system.locale))</SystemLocale>
              <UILanguage>\(esc(template.system.locale))</UILanguage>
              <UserLocale>\(esc(template.system.locale))</UserLocale>
            """)

        var shell = """

              <TimeZone>\(esc(template.system.timeZone))</TimeZone>
              <OOBE>
                <HideEULAPage>\(template.oobe.hideEULA)</HideEULAPage>
                <HideOEMRegistrationScreen>\(template.oobe.hideOEMRegistration)</HideOEMRegistrationScreen>
                <HideOnlineAccountScreens>\(template.oobe.hideOnlineAccountScreens)</HideOnlineAccountScreens>
                <HideWirelessSetupInOOBE>\(template.oobe.hideWirelessSetup)</HideWirelessSetupInOOBE>
                <ProtectYourPC>\(template.oobe.protectYourPC)</ProtectYourPC>
                <SkipMachineOOBE>\(template.oobe.skipMachineOOBE)</SkipMachineOOBE>
                <SkipUserOOBE>\(template.oobe.skipUserOOBE)</SkipUserOOBE>
              </OOBE>
            """

        if let accounts = userAccounts() {
            shell += accounts
        }
        if let autoLogon = autoLogonBlock() {
            shell += autoLogon
        }
        if let commands = firstLogonCommands() {
            shell += commands
        }

        body += component("Microsoft-Windows-Shell-Setup", body: shell)
        body += "\n</settings>"
        return body
    }

    private func userAccounts() -> String? {
        var locals: [String] = []

        if template.admin.enabled && !template.admin.username.isEmpty {
            locals.append("""

                        <LocalAccount wcm:action="add">
                          <Name>\(esc(template.admin.username))</Name>
                          <DisplayName>\(esc(template.admin.displayName))</DisplayName>
                          <Description>\(esc(template.admin.accountDescription))</Description>
                          <Group>Administrators</Group>
                          <Password>
                            <Value>\(esc(secrets.adminPassword))</Value>
                            <PlainText>true</PlainText>
                          </Password>
                        </LocalAccount>
                """)
        }

        if template.endUser.mode == .createLocalAccount && !template.endUser.username.isEmpty {
            locals.append("""

                        <LocalAccount wcm:action="add">
                          <Name>\(esc(template.endUser.username))</Name>
                          <DisplayName>\(esc(template.endUser.displayName.isEmpty ? template.endUser.username : template.endUser.displayName))</DisplayName>
                          <Description>Created by ImageHub</Description>
                          <Group>\(template.endUser.administrator ? "Administrators" : "Users")</Group>
                          <Password>
                            <Value>\(esc(secrets.userPassword))</Value>
                            <PlainText>true</PlainText>
                          </Password>
                        </LocalAccount>
                """)
        }

        guard !locals.isEmpty else { return nil }

        var block = "\n      <UserAccounts>"
        if template.admin.enableBuiltInAdministrator && !secrets.adminPassword.isEmpty {
            block += """

                    <AdministratorPassword>
                      <Value>\(esc(secrets.adminPassword))</Value>
                      <PlainText>true</PlainText>
                    </AdministratorPassword>
                """
        }
        block += "\n        <LocalAccounts>\(locals.joined())\n        </LocalAccounts>"
        block += "\n      </UserAccounts>"
        return block
    }

    private func autoLogonBlock() -> String? {
        guard template.admin.enabled,
              template.admin.autoLogonCount > 0,
              !template.admin.username.isEmpty,
              !secrets.adminPassword.isEmpty
        else { return nil }

        return """

              <AutoLogon>
                <Enabled>true</Enabled>
                <Username>\(esc(template.admin.username))</Username>
                <LogonCount>\(template.admin.autoLogonCount)</LogonCount>
                <Password>
                  <Value>\(esc(secrets.adminPassword))</Value>
                  <PlainText>true</PlainText>
                </Password>
              </AutoLogon>
            """
    }

    private func firstLogonCommands() -> String? {
        // Provisioning runs from C:\ImageHub (staged during specialize); the USB
        // search is a fallback in case staging didn't happen.
        let launcher = """
            $p = 'C:\\ImageHub\\Provision.ps1'; \
            if (-not (Test-Path $p)) { \
            $p = Get-PSDrive -PSProvider FileSystem | \
            ForEach-Object { Join-Path $_.Root 'ImageHub\\Provision.ps1' } | \
            Where-Object { Test-Path $_ } | Select-Object -First 1 }; \
            if ($p) { & $p }
            """

        var commands: [(String, String)] = [
            (powershellCommand(launcher), "ImageHub provisioning")
        ]
        if template.admin.hideFromLoginScreen && !template.admin.username.isEmpty {
            commands.append((
                #"cmd /c reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\UserList" /v "#
                    + "\(template.admin.username) /t REG_DWORD /d 0 /f",
                "Hide the IT admin account"
            ))
        }

        var block = "\n      <FirstLogonCommands>"
        for (index, command) in commands.enumerated() {
            block += """

                    <SynchronousCommand wcm:action="add">
                      <Order>\(index + 1)</Order>
                      <CommandLine>\(esc(command.0))</CommandLine>
                      <Description>\(esc(command.1))</Description>
                      <RequiresUserInput>false</RequiresUserInput>
                    </SynchronousCommand>
                """
        }
        block += "\n      </FirstLogonCommands>"
        return block
    }

    // MARK: - XML plumbing

    private func component(_ name: String, body: String) -> String {
        guard !body.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return "" }
        return """


              <component name="\(name)" processorArchitecture="\(architecture)" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">\(body)
              </component>
            """
    }

    private func runSynchronous(_ commands: [String]) -> String? {
        guard !commands.isEmpty else { return nil }
        var block = "\n      <RunSynchronous>"
        for (index, command) in commands.enumerated() {
            block += """

                    <RunSynchronousCommand wcm:action="add">
                      <Order>\(index + 1)</Order>
                      <Path>\(esc(command))</Path>
                    </RunSynchronousCommand>
                """
        }
        block += "\n      </RunSynchronous>"
        return block
    }

    private func powershellCommand(_ script: String) -> String {
        let collapsed = script
            .replacingOccurrences(of: "\\\n", with: "")
            .split(separator: "\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .joined(separator: " ")
        return "powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"\(collapsed)\""
    }

    private func esc(_ value: String) -> String {
        value
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&apos;")
    }
}
