import Foundation

/// Builds the `configuration.xml` the Office Deployment Tool consumes.
///
/// Generated here rather than assembled by `Provision.ps1` for the same reason
/// `autounattend.xml` is: it can be checked before the drive is written. A
/// malformed answer file costs a technician an afternoon at a bench, and a
/// malformed Office config costs the same afternoon a few steps later.
///
/// Reference: "Configuration options for the Office Deployment Tool".
enum OfficeConfigBuilder {
    static let fileName = "configuration.xml"

    /// Where the staged Office source lands on the target.
    ///
    /// `Stage.cmd` copies the payload to `C:\ImageHub`, so this is known at build
    /// time. `Provision.ps1` corrects it if a run ends up working from the media
    /// instead, which happens when staging never got the chance.
    static let bundledSourcePath = #"C:\ImageHub\Office"#

    /// Element order inside `<Configuration>` is not enforced the way the unattend
    /// schema is, but the ODT documents this sequence and there is nothing to gain
    /// from deviating: Add, RemoveMSI, Display, Property, Updates.
    static func xml(for template: DeploymentTemplate) -> String {
        let office = template.microsoft365
        let bundlesSource = !office.sourcePath.isEmpty
        // An empty language follows the rest of the template rather than making the
        // operator type "en-us" twice. The ODT wants a lowercased locale tag.
        let language = office.language.isEmpty
            ? template.system.locale.lowercased()
            : office.language.lowercased()

        var product = """
              <Product ID="\(esc(office.product.productID))">
                  <Language ID="\(esc(language))" />
            """
        // Sorted so the same template always produces byte-identical XML; a diff
        // that reorders itself run to run is a diff nobody reads.
        for app in office.excludedApps.sorted() {
            product += """

                    <ExcludeApp ID="\(esc(app))" />
                """
        }
        product += """

              </Product>
            """

        // SourcePath points the Deployment Tool at a local copy instead of the CDN, so
        // the install works with no internet at all. AllowCdnFallback keeps a partial
        // or mismatched local source from being fatal on a machine that *is* online.
        var addAttributes = "OfficeClientEdition=\"\(esc(office.architecture))\""
        addAttributes += " Channel=\"\(esc(office.channel.channelID))\""
        if bundlesSource {
            addAttributes += " SourcePath=\"\(esc(bundledSourcePath))\""
            addAttributes += " AllowCdnFallback=\"True\""
        }

        var body = """
              <Add \(addAttributes)>
            \(product)
              </Add>
            """

        if office.removeExistingOffice {
            body += """

                  <RemoveMSI />
                """
        }

        // Level None is the whole point of an unattended install; AcceptEULA
        // suppresses the licence prompt that would otherwise wait for a human.
        body += """

              <Display Level="None" AcceptEULA="TRUE" />
              <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />
            """

        // AUTOACTIVATE is only meaningful for volume products; on a subscription
        // product Office signs in instead and the property is ignored, so it is
        // written only where it does something.
        if office.autoActivate && office.product.isVolume {
            body += """

                  <Property Name="AUTOACTIVATE" Value="1" />
                """
        }

        body += """

              <Updates Enabled="\(office.keepUpdatesEnabled ? "TRUE" : "FALSE")" />
            """

        return """
            <?xml version="1.0" encoding="utf-8"?>
            <!-- Generated by ImageHub. Edits here are overwritten on the next build. -->
            <Configuration>
            \(body)
            </Configuration>

            """
    }

    private static func esc(_ value: String) -> String {
        value
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&apos;")
    }
}
