import Foundation

/// Builds the `configuration.xml` the Office Deployment Tool consumes.
///
/// Generated here rather than assembled by `Provision.ps1` for the same reason
/// `autounattend.xml` is: it can be checked before the drive is written. A
/// malformed answer file costs a technician an afternoon at a bench, and a
/// malformed Office config costs the same afternoon a few steps later.
///
/// Reference: "Configuration options for the Office Deployment Tool".
enum OfficeConfigBuilder {
    static let fileName = "configuration.xml"

    /// Element order inside `<Configuration>` is not enforced the way the unattend
    /// schema is, but the ODT documents this sequence and there is nothing to gain
    /// from deviating: Add, RemoveMSI, Display, Property, Updates.
    static func xml(for template: DeploymentTemplate) -> String {
        let office = template.microsoft365
        // The ODT only speaks in exclusions, so the template's "install these" list
        // is inverted here. Anything not asked for is left out, which also means a
        // new app appearing in a future Office release is excluded by default rather
        // than silently installed.
        let wanted = Set(office.includedApps)
        let excluded = (
            Microsoft365Spec.availableApps.map(\.id).filter { !wanted.contains($0) }
                + Microsoft365Spec.alwaysExcluded
        ).sorted()

        var product = """
              <Product ID="\(esc(Microsoft365Spec.productID))">
                  <Language ID="\(esc(template.system.locale.lowercased()))" />
            """
        for app in excluded {
            product += """

                    <ExcludeApp ID="\(esc(app))" />
                """
        }
        product += """

              </Product>
            """

        // RemoveMSI, Display and Updates are not choices. An older MSI Office left
        // in place breaks the new install; a visible installer waits for a human who
        // is not there; and Office with updates switched off is a liability.
        return """
            <?xml version="1.0" encoding="utf-8"?>
            <!-- Generated by ImageHub. Edits here are overwritten on the next build. -->
            <Configuration>
              <Add OfficeClientEdition="\(esc(Microsoft365Spec.architecture))" Channel="\(esc(Microsoft365Spec.channelID))">
            \(product)
              </Add>
              <RemoveMSI />
              <Display Level="None" AcceptEULA="TRUE" />
              <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />
              <Updates Enabled="TRUE" />
            </Configuration>

            """
    }

    private static func esc(_ value: String) -> String {
        value
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&apos;")
    }
}
